### PR TITLE
Handle communication to backend correctly

### PR DESCRIPTION
**Pull request by alejx**
This PR:
- Add axios and use it to POST instead of `fetch`
- Store number value in the props instead of string values
- Fix some alignment issues

### CODE REVIEW

**Comment by eosza** [comment]
@alejx Why are we making this change?

**Comment by rafibarash** [comment]
also curious why you are changing fetch to axios?

**Comment by alejx** [comment]
When I run on my machine, the frontend always fetch from 3000, not 8080. Are there any special instructions to fetch from 8080 other than just run with `npm start`?

**Comment by ZeyuGao1** [comment]
I used to use axios to fetch the data, and they changed it back and works.
Why we have axios again now?

**Comment by alejx** [comment]
image
This is what I got when on the master branch, the request url has port number 3000, not 8080; and there's no response from the backend. I assumed the request was sent to 3000.

I'll revert unrelated changes back soon.

**Comment by rafibarash** [comment]
@alejx Can you post a picture of your package.json file? If you're based off the master branch there should be a line around line 17 that reads, `"proxy": "http://localhost:8080"`. This fixes the CORS issue for development by forwarding api requests to the backend

**Comment by alejx** [comment]
@rafibarash Yes I noticed that line, but the requested URL in the headers is still 3000, which is fine, and I log in the backend and confirm that the backend received the POST. The thing that confused me is that there's no response from the backend, but it should be another problem,

**Pull request closed without merging**
