### PR TITLE
Fix coding style

### PR DESCRIPTION
**Pull request by alejx**
using yarn prettier --write "src/**/*.js"

### CODE REVIEW

**Comment by rafibarash** [comment]
I'll approve this. Prettier should format all future code on git commits

**Comment by rafibarash** [comment]
On second thought, this might make some nasty merge conflicts for other development branches, and all future code should be autoformatted thanks to the "husky" package. Honestly don't think this is worth merging in

**Comment by alejx** [comment]
The reason why I created this PR is that husky only check the files in the stage when you commit.

**Comment by rafibarash** [comment]
Ohhh I see, in that case I'll approve

**Pull request merged**
